# Generated by Django 2.1.4 on 2018-12-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Operation'),
        ),
    ]
