# Generated by Django 2.1.4 on 2019-01-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20190106_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_set', to='category.Category'),
        ),
    ]
